name: LazerOnigokko
version: 1.0-SNAPSHOT
main: jp.simplespace.lazeronigokko.LazerOnigokko
api-version: 1.16
authors: [ Matchan ]
description: 謎のレーザー鬼ごっこ
website: https://simplespace.jp
commands:
  setup:
    description: セットアップを実行するコマンド
    usage: /<command>
    permission: lazeronigokko.command.setup
  gui:
    description: GUIを開くコマンド
    usage: /<command> <GUI名>
    permission: lazeronigokko.command.gui
permissions:
  lazeronigokko.*:
    description: すべての権限
    default: op
    children:
      lazeronigokko.command.*: true
  lazeronigokko.command.*:
    description: コマンドのすべての権限
    default: op
    children:
      lazeronigokko.command.setup: true
      lazeronigokko.command.gui: true
  lazeronigokko.command.setup:
    description: セットアップコマンドの権限
    default: op
  lazeronigokko.command.gui:
    description: GUIコマンドの権限
    default: op